name: Tests

on: push

jobs:
  run-linters:
    name: npm run test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: [4.2]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: superchargejs/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm install
    - run: npm test -- --coverage


    - uses: codecov/codecov-action@v1
      with:
        # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage/clover.xml # optional
        flags: unit # optional
        # name: codecov-umbrella # optional
        # fail_ci_if_error: true # optional (default = false)